version: '3.8'

services:
  flask_app:
    container_name: flask_app
    restart: always
    image: public.ecr.aws/dissco/bicikl-linkages-back-end:latest
    volumes: [ './flask_app:/flask_app' ]   
  front_end:
    container_name: front_end
    restart: always
    image: public.ecr.aws/dissco/bicikl-linkages-front-end:latest
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
