version: '3.8'

services:
  flask_app:
    container_name: flask_api
    restart: always
    build: ./flask_app
    volumes: ['./flask_app:/flask_app']  # left is api folder, right is wkdir defined in flask_app/Dockerfile
    networks:
      - linkage
    ports:
      - "5000:5000"
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - linkage
    expose:
      - "8080"
    ports:
      - "80:8080"
networks:
  linkage: